/* Страны */
INSERT INTO country(cnt_alpha2,  cnt_alpha3,  cnt_numeric,  cnt_eng_name,  cnt_name,  cnt_keywords) VALUES
('AD', 'AND', 20, 'ANDORRA', 'Андорра', NULL),
('AE', 'ARE', 784, 'UNITED ARAB EMIRATES', 'Объединенные Арабские Эмираты', 'ОАЭ UAE'),
('AF', 'AFG', 4, 'AFGHANISTAN', 'Афганистан', NULL),
('AG', 'ATG', 28, 'ANTIGUA AND BARBUDA', 'Антигуа и Барбуда', NULL),
('AI', 'AIA', 660, 'ANGUILLA', 'Ангилья', NULL),
('AL', 'ALB', 8, 'ALBANIA', 'Албания', NULL),
('AM', 'ARM', 51, 'ARMENIA', 'Армения', NULL),
('AN', 'ANT', 530, 'NETHERLANDS ANTILLES', 'Нидерландские Антилы', NULL),
('AO', 'AGO', 24, 'ANGOLA', 'Ангола', NULL),
('AQ', 'ATA', 10, 'ANTARCTICA', 'Антарктида', NULL),
('AR', 'ARG', 32, 'ARGENTINA', 'Аргентина', NULL),
('AS', 'ASM', 16, 'AMERICAN SAMOA', 'Американское Самоа', NULL),
('AT', 'AUT', 40, 'AUSTRIA', 'Австрия', NULL),
('AU', 'AUS', 36, 'AUSTRALIA', 'Австралия', NULL),
('AW', 'ABW', 533, 'ARUBA', 'Аруба', NULL),
('AX', 'ALA', 248, 'ALAND ISLANDS', 'Эландские острова', NULL),
('AZ', 'AZE', 31, 'AZERBAIJAN', 'Азербайджан', NULL),
('BA', 'BIH', 70, 'BOSNIA AND HERZEGOVINA', 'Босния и Герцеговина', NULL),
('BB', 'BRB', 52, 'BARBADOS', 'Барбадос', NULL),
('BD', 'BGD', 50, 'BANGLADESH', 'Бангладеш', NULL),
('BE', 'BEL', 56, 'BELGIUM', 'Бельгия', NULL),
('BF', 'BFA', 854, 'BURKINA FASO', 'Буркина-Фасо', NULL),
('BG', 'BGR', 100, 'BULGARIA', 'Болгария', NULL),
('BH', 'BHR', 48, 'BAHRAIN', 'Бахрейн', NULL),
('BI', 'BDI', 108, 'BURUNDI', 'Бурунди', NULL),
('BJ', 'BEN', 204, 'BENIN', 'Бенин', NULL),
('BL', 'BLM', 652, 'SAINT BARTHELEMY', 'Сен-Бартельми', NULL),
('BM', 'BMU', 60, 'BERMUDA', 'Бермуды', NULL),
('BN', 'BRN', 96, 'BRUNEI DARUSSALAM', 'Бруней-Даруссалам', NULL),
('BO', 'BOL', 68, 'BOLIVIA,  PLURINATIONAL STATE OF', 'Боливия', NULL),
('BR', 'BRA', 76, 'BRAZIL', 'Бразилия', NULL),
('BS', 'BHS', 44, 'BAHAMAS', 'Багамы', NULL),
('BT', 'BTN', 64, 'BHUTAN', 'Бутан', NULL),
('BV', 'BVT', 74, 'BOUVET ISLAND', 'Остров Буве', NULL),
('BW', 'BWA', 72, 'BOTSWANA', 'Ботсвана', NULL),
('BY', 'BLR', 112, 'BELARUS', 'Беларусь', 'Белоруссия'),
('BZ', 'BLZ', 84, 'BELIZE', 'Белиз', NULL),
('CA', 'CAN', 124, 'CANADA', 'Канада', NULL),
('CC', 'CCK', 166, 'COCOS (KEELING) ISLANDS', 'Кокосовые (Килинг) острова', NULL),
('CD', 'COD', 180, 'CONGO,  THE DEMOCRATIC REPUBLIC OF THE', 'Конго,  Демократическая Республика', NULL),
('CF', 'CAF', 140, 'CENTRAL AFRICAN REPUBLIC', 'Центрально-Африканская Республика', NULL),
('CG', 'COG', 178, 'CONGO', 'Конго', NULL),
('CH', 'CHE', 756, 'SWITZERLAND', 'Швейцария', NULL),
('CI', 'CIV', 384, 'COTE D''IVOIRE', 'Кот д''Ивуар', NULL),
('CK', 'COK', 184, 'COOK ISLANDS', 'Острова Кука', NULL),
('CL', 'CHL', 152, 'CHILE', 'Чили', NULL),
('CM', 'CMR', 120, 'CAMEROON', 'Камерун', NULL),
('CN', 'CHN', 156, 'CHINA', 'Китай', 'КНР'),
('CO', 'COL', 170, 'COLOMBIA', 'Колумбия', NULL),
('CP', NULL, NULL, 'Clipperton Island', 'Остров Клиппертон', NULL),
('CR', 'CRI', 188, 'COSTA RICA', 'Коста-Рика', NULL),
('CU', 'CUB', 192, 'CUBA', 'Куба', NULL),
('CV', 'CPV', 132, 'CAPE VERDE', 'Кабо-Верде', NULL),
('CX', 'CXR', 162, 'CHRISTMAS ISLAND', 'Остров Рождества', NULL),
('CY', 'CYP', 196, 'CYPRUS', 'Кипр', NULL),
('CZ', 'CZE', 203, 'CZECH REPUBLIC', 'Чешская Республика', NULL),
('DE', 'DEU', 276, 'GERMANY', 'Германия', 'ФРГ'),
('DJ', 'DJI', 262, 'DJIBOUTI', 'Джибути', NULL),
('DK', 'DNK', 208, 'DENMARK', 'Дания', NULL),
('DM', 'DMA', 212, 'DOMINICA', 'Доминика', NULL),
('DO', 'DOM', 214, 'DOMINICAN REPUBLIC', 'Доминиканская Республика', NULL),
('DZ', 'DZA', 12, 'ALGERIA', 'Алжир', NULL),
('EC', 'ECU', 218, 'ECUADOR', 'Эквадор', NULL),
('EE', 'EST', 233, 'ESTONIA', 'Эстония', NULL),
('EG', 'EGY', 818, 'EGYPT', 'Египет', NULL),
('EH', 'ESH', 732, 'WESTERN SAHARA', 'Западная Сахара', NULL),
('ER', 'ERI', 232, 'ERITREA', 'Эритрея', NULL),
('ES', 'ESP', 724, 'SPAIN', 'Испания', NULL),
('ET', 'ETH', 231, 'ETHIOPIA', 'Эфиопия', NULL),
('EU', NULL, NULL, 'European Union', 'Евросоюз', 'Европейский союз ЕС'),
('FI', 'FIN', 246, 'FINLAND', 'Финляндия', NULL),
('FJ', 'FJI', 242, 'FIJI', 'Фиджи', NULL),
('FK', 'FLK', 238, 'FALKLAND ISLANDS (MALVINAS)', 'Фолклендские острова (Мальвинские)', NULL),
('FM', 'FSM', 583, 'MICRONESIA,  FEDERATED STATES OF', 'Микронезия', NULL),
('FO', 'FRO', 234, 'FAROE ISLANDS', 'Фарерские острова', NULL),
('FR', 'FRA', 250, 'FRANCE', 'Франция', NULL),
('GA', 'GAB', 266, 'GABON', 'Габон', NULL),
('GB', 'GBR', 826, 'UNITED KINGDOM', 'Великобритания', 'Соединенное Королевство Великобритании и Северной Ирландии Англия Шотландия Уэльс Great Britain Northern Ireland England Scotland Wales UK ENG'),
('GD', 'GRD', 308, 'GRENADA', 'Гренада', NULL),
('GE', 'GEO', 268, 'GEORGIA', 'Грузия', NULL),
('GF', 'GUF', 254, 'FRENCH GUIANA', 'Французская Гвиана', NULL),
('GG', 'GGY', 831, 'GUERNSEY', 'Гернси', NULL),
('GH', 'GHA', 288, 'GHANA', 'Гана', NULL),
('GI', 'GIB', 292, 'GIBRALTAR', 'Гибралтар', NULL),
('GL', 'GRL', 304, 'GREENLAND', 'Гренландия', NULL),
('GM', 'GMB', 270, 'GAMBIA', 'Гамбия', NULL),
('GN', 'GIN', 324, 'GUINEA', 'Гвинея', NULL),
('GP', 'GLP', 312, 'GUADELOUPE', 'Гваделупа', NULL),
('GQ', 'GNQ', 226, 'EQUATORIAL GUINEA', 'Экваториальная Гвинея', NULL),
('GR', 'GRC', 300, 'GREECE', 'Греция', NULL),
('GS', 'SGS', 239, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'Южная Джорджия и Южные Сандвичевы острова', NULL),
('GT', 'GTM', 320, 'GUATEMALA', 'Гватемала', NULL),
('GU', 'GUM', 316, 'GUAM', 'Гуам', NULL),
('GW', 'GNB', 624, 'GUINEA-BISSAU', 'Гвинея-Бисау', NULL),
('GY', 'GUY', 328, 'GUYANA', 'Гайана', NULL),
('HK', 'HKG', 344, 'HONG KONG', 'Гонконг', NULL),
('HM', 'HMD', 334, 'HEARD ISLAND AND MCDONALD ISLANDS', 'Остров Херд и острова Макдональд', NULL),
('HN', 'HND', 340, 'HONDURAS', 'Гондурас', NULL),
('HR', 'HRV', 191, 'CROATIA', 'Хорватия', NULL),
('HT', 'HTI', 332, 'HAITI', 'Гаити', NULL),
('HU', 'HUN', 348, 'HUNGARY', 'Венгрия', NULL),
('ID', 'IDN', 360, 'INDONESIA', 'Индонезия', NULL),
('IE', 'IRL', 372, 'IRELAND', 'Ирландия', NULL),
('IL', 'ISR', 376, 'ISRAEL', 'Израиль', NULL),
('IM', 'IMN', 833, 'ISLE OF MAN', 'Остров Мэн', NULL),
('IN', 'IND', 356, 'INDIA', 'Индия', NULL),
('IO', 'IOT', 86, 'BRITISH INDIAN OCEAN TERRITORY', 'Британская территория в Индийском океане', NULL),
('IQ', 'IRQ', 368, 'IRAQ', 'Ирак', NULL),
('IR', 'IRN', 364, 'IRAN,  ISLAMIC REPUBLIC OF', 'Иран', NULL),
('IS', 'ISL', 352, 'ICELAND', 'Исландия', NULL),
('IT', 'ITA', 380, 'ITALY', 'Италия', NULL),
('JE', 'JEY', 832, 'JERSEY', 'Джерси', NULL),
('JM', 'JAM', 388, 'JAMAICA', 'Ямайка', NULL),
('JO', 'JOR', 400, 'JORDAN', 'Иордания', NULL),
('JP', 'JPN', 392, 'JAPAN', 'Япония', NULL),
('KE', 'KEN', 404, 'KENYA', 'Кения', NULL),
('KG', 'KGZ', 417, 'KYRGYZSTAN', 'Киргизия', NULL),
('KH', 'KHM', 116, 'CAMBODIA', 'Камбоджа', NULL),
('KI', 'KIR', 296, 'KIRIBATI', 'Кирибати', NULL),
('KM', 'COM', 174, 'COMOROS', 'Коморы', NULL),
('KN', 'KNA', 659, 'SAINT KITTS AND NEVIS', 'Сент-Китс и Невис', NULL),
('KP', 'PRK', 408, 'KOREA,  DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Северная Корея', NULL),
('KR', 'KOR', 410, 'KOREA,  REPUBLIC OF', 'Южная Корея', NULL),
('KW', 'KWT', 414, 'KUWAIT', 'Кувейт', NULL),
('KY', 'CYM', 136, 'CAYMAN ISLANDS', 'Острова Кайман', NULL),
('KZ', 'KAZ', 398, 'KAZAKHSTAN', 'Казахстан', NULL),
('LA', 'LAO', 418, 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Лаос', NULL),
('LB', 'LBN', 422, 'LEBANON', 'Ливан', NULL),
('LC', 'LCA', 662, 'SAINT LUCIA', 'Сент-Люсия', NULL),
('LI', 'LIE', 438, 'LIECHTENSTEIN', 'Лихтенштейн', NULL),
('LK', 'LKA', 144, 'SRI LANKA', 'Шри-Ланка', NULL),
('LR', 'LBR', 430, 'LIBERIA', 'Либерия', NULL),
('LS', 'LSO', 426, 'LESOTHO', 'Лесото', NULL),
('LT', 'LTU', 440, 'LITHUANIA', 'Литва', NULL),
('LU', 'LUX', 442, 'LUXEMBOURG', 'Люксембург', NULL),
('LV', 'LVA', 428, 'LATVIA', 'Латвия', NULL),
('LY', 'LBY', 434, 'LIBYAN ARAB JAMAHIRIYA', 'Ливия', 'Ливийская Арабская Джамахирия'),
('MA', 'MAR', 504, 'MOROCCO', 'Марокко', NULL),
('MC', 'MCO', 492, 'MONACO', 'Монако', NULL),
('MD', 'MDA', 498, 'MOLDOVA,  REPUBLIC OF', 'Молдова', NULL),
('ME', 'MNE', 499, 'MONTENEGRO', 'Черногория', NULL),
('MF', 'MAF', 663, 'SAINT MARTIN', 'Остров Святого Мартина', NULL),
('MG', 'MDG', 450, 'MADAGASCAR', 'Мадагаскар', NULL),
('MH', 'MHL', 584, 'MARSHALL ISLANDS', 'Маршалловы острова', NULL),
('MK', 'MKD', 807, 'MACEDONIA,  THE FORMER YUGOSLAV REPUBLIC OF', 'Македония', NULL),
('ML', 'MLI', 466, 'MALI', 'Мали', NULL),
('MM', 'MMR', 104, 'MYANMAR', 'Мьянма', NULL),
('MN', 'MNG', 496, 'MONGOLIA', 'Монголия', NULL),
('MO', 'MAC', 446, 'MACAO', 'Макао', NULL),
('MP', 'MNP', 580, 'NORTHERN MARIANA ISLANDS', 'Северные Марианские острова', NULL),
('MQ', 'MTQ', 474, 'MARTINIQUE', 'Мартиника', NULL),
('MR', 'MRT', 478, 'MAURITANIA', 'Мавритания', NULL),
('MS', 'MSR', 500, 'MONTSERRAT', 'Монтсеррат', NULL),
('MT', 'MLT', 470, 'MALTA', 'Мальта', NULL),
('MU', 'MUS', 480, 'MAURITIUS', 'Маврикий', NULL),
('MV', 'MDV', 462, 'MALDIVES', 'Мальдивы', NULL),
('MW', 'MWI', 454, 'MALAWI', 'Малави', NULL),
('MX', 'MEX', 484, 'MEXICO', 'Мексика', NULL),
('MY', 'MYS', 458, 'MALAYSIA', 'Малайзия', NULL),
('MZ', 'MOZ', 508, 'MOZAMBIQUE', 'Мозамбик', NULL),
('NA', 'NAM', 516, 'NAMIBIA', 'Намибия', NULL),
('NC', 'NCL', 540, 'NEW CALEDONIA', 'Новая Каледония', NULL),
('NE', 'NER', 562, 'NIGER', 'Нигер', NULL),
('NF', 'NFK', 574, 'NORFOLK ISLAND', 'Остров Норфолк', NULL),
('NG', 'NGA', 566, 'NIGERIA', 'Нигерия', NULL),
('NI', 'NIC', 558, 'NICARAGUA', 'Никарагуа', NULL),
('NL', 'NLD', 528, 'NETHERLANDS', 'Нидерланды', 'Голландия'),
('NO', 'NOR', 578, 'NORWAY', 'Норвегия', NULL),
('NP', 'NPL', 524, 'NEPAL', 'Непал', NULL),
('NR', 'NRU', 520, 'NAURU', 'Науру', NULL),
('NU', 'NIU', 570, 'NIUE', 'Ниуэ', NULL),
('NZ', 'NZL', 554, 'NEW ZEALAND', 'Новая Зеландия', NULL),
('OM', 'OMN', 512, 'OMAN', 'Оман', NULL),
('PA', 'PAN', 591, 'PANAMA', 'Панама', NULL),
('PE', 'PER', 604, 'PERU', 'Перу', NULL),
('PF', 'PYF', 258, 'FRENCH POLYNESIA', 'Французская Полинезия', NULL),
('PG', 'PNG', 598, 'PAPUA NEW GUINEA', 'Папуа-Новая Гвинея', NULL),
('PH', 'PHL', 608, 'PHILIPPINES', 'Филиппины', NULL),
('PK', 'PAK', 586, 'PAKISTAN', 'Пакистан', NULL),
('PL', 'POL', 616, 'POLAND', 'Польша', NULL),
('PM', 'SPM', 666, 'SAINT PIERRE AND MIQUELON', 'Сен-Пьер и Микелон', NULL),
('PN', 'PCN', 612, 'PITCAIRN', 'Питкерн', NULL),
('PR', 'PRI', 630, 'PUERTO RICO', 'Пуэрто-Рико', NULL),
('PS', 'PSE', 275, 'PALESTINIAN TERRITORY,  OCCUPIED', 'Палестина', 'Палестинская территория'),
('PT', 'PRT', 620, 'PORTUGAL', 'Португалия', NULL),
('PW', 'PLW', 585, 'PALAU', 'Палау', NULL),
('PY', 'PRY', 600, 'PARAGUAY', 'Парагвай', NULL),
('QA', 'QAT', 634, 'QATAR', 'Катар', NULL),
('RE', 'REU', 638, 'REUNION', 'Реюньон', NULL),
('RO', 'ROU', 642, 'ROMANIA', 'Румыния', NULL),
('RS', 'SRB', 688, 'SERBIA', 'Сербия', NULL),
('RU', 'RUS', 643, 'RUSSIAN FEDERATION', 'Россия', 'Российская Федерация РФ Russia'),
('RW', 'RWA', 646, 'RWANDA', 'Руанда', NULL),
('SA', 'SAU', 682, 'SAUDI ARABIA', 'Саудовская Аравия', NULL),
('SB', 'SLB', 90, 'SOLOMON ISLANDS', 'Соломоновы острова', NULL),
('SC', 'SYC', 690, 'SEYCHELLES', 'Сейшелы', NULL),
('SD', 'SDN', 736, 'SUDAN', 'Судан', NULL),
('SE', 'SWE', 752, 'SWEDEN', 'Швеция', NULL),
('SG', 'SGP', 702, 'SINGAPORE', 'Сингапур', NULL),
('SH', 'SHN', 654, 'SAINT HELENA,  ASCENSION AND TRISTAN DA CUNHA', 'Святая Елена', NULL),
('SI', 'SVN', 705, 'SLOVENIA', 'Словения', NULL),
('SJ', 'SJM', 744, 'SVALBARD AND JAN MAYEN', 'Шпицберген и Ян Майен', NULL),
('SK', 'SVK', 703, 'SLOVAKIA', 'Словакия', NULL),
('SL', 'SLE', 694, 'SIERRA LEONE', 'Сьерра-Леоне', NULL),
('SM', 'SMR', 674, 'SAN MARINO', 'Сан-Марино', NULL),
('SN', 'SEN', 686, 'SENEGAL', 'Сенегал', NULL),
('SO', 'SOM', 706, 'SOMALIA', 'Сомали', NULL),
('SR', 'SUR', 740, 'SURINAME', 'Суринам', NULL),
('ST', 'STP', 678, 'SAO TOME AND PRINCIPE', 'Сан-Томе и Принсипи', NULL),
('SV', 'SLV', 222, 'EL SALVADOR', 'Эль-Сальвадор', NULL),
('SY', 'SYR', 760, 'SYRIAN ARAB REPUBLIC', 'Сирия', NULL),
('SZ', 'SWZ', 748, 'SWAZILAND', 'Свазиленд', NULL),
('TC', 'TCA', 796, 'TURKS AND CAICOS ISLANDS', 'Острова Теркс и Кайкос', NULL),
('TD', 'TCD', 148, 'CHAD', 'Чад', NULL),
('TF', 'ATF', 260, 'FRENCH SOUTHERN TERRITORIES', 'Французские Южные территории', NULL),
('TG', 'TGO', 768, 'TOGO', 'Того', NULL),
('TH', 'THA', 764, 'THAILAND', 'Таиланд', NULL),
('TJ', 'TJK', 762, 'TAJIKISTAN', 'Таджикистан', NULL),
('TK', 'TKL', 772, 'TOKELAU', 'Токелау', NULL),
('TL', 'TLS', 626, 'TIMOR-LESTE', 'Тимор-Лесте', NULL),
('TM', 'TKM', 795, 'TURKMENISTAN', 'Туркмения', NULL),
('TN', 'TUN', 788, 'TUNISIA', 'Тунис', NULL),
('TO', 'TON', 776, 'TONGA', 'Тонга', NULL),
('TR', 'TUR', 792, 'TURKEY', 'Турция', NULL),
('TT', 'TTO', 780, 'TRINIDAD AND TOBAGO', 'Тринидад и Тобаго', NULL),
('TV', 'TUV', 798, 'TUVALU', 'Тувалу', NULL),
('TW', 'TWN', 158, 'TAIWAN,  PROVINCE OF CHINA', 'Тайвань (Китай)', 'КНР'),
('TZ', 'TZA', 834, 'TANZANIA,  UNITED REPUBLIC OF', 'Танзания', NULL),
('UA', 'UKR', 804, 'UKRAINE', 'Украина', NULL),
('UG', 'UGA', 800, 'UGANDA', 'Уганда', NULL),
('UM', 'UMI', 581, 'UNITED STATES MINOR OUTLYING ISLANDS', 'Малые Тихоокеанские отдаленные острова Соединенных Штатов', NULL),
('US', 'USA', 840, 'UNITED STATES', 'США', 'Соединенные Штаты Америки'),
('UY', 'URY', 858, 'URUGUAY', 'Уругвай', NULL),
('UZ', 'UZB', 860, 'UZBEKISTAN', 'Узбекистан', NULL),
('VA', 'VAT', 336, 'HOLY SEE (VATICAN CITY STATE)', 'Ватикан', 'Папский Престол (Государство - город Ватикан)'),
('VC', 'VCT', 670, 'SAINT VINCENT AND THE GRENADINES', 'Сент-Винсент и Гренадины', NULL),
('VE', 'VEN', 862, 'VENEZUELA,  BOLIVARIAN REPUBLIC OF', 'Венесуэла', NULL),
('VG', 'VGB', 92, 'VIRGIN ISLANDS,  BRITISH', 'Виргинские острова,  Британские', NULL),
('VI', 'VIR', 850, 'VIRGIN ISLANDS,  U.S.', 'Виргинские острова,  США', NULL),
('VN', 'VNM', 704, 'VIET NAM', 'Вьетнам', NULL),
('VU', 'VUT', 548, 'VANUATU', 'Вануату', NULL),
('WF', 'WLF', 876, 'WALLIS AND FUTUNA', 'Уоллис и Футуна', NULL),
('WS', 'WSM', 882, 'SAMOA', 'Самоа', NULL),
('YE', 'YEM', 887, 'YEMEN', 'Йемен', NULL),
('YT', 'MYT', 175, 'MAYOTTE', 'Майотта', NULL),
('ZA', 'ZAF', 710, 'SOUTH AFRICA', 'Южная Африка', 'ЮАР'),
('ZM', 'ZMB', 894, 'ZAMBIA', 'Замбия', NULL),
('ZW', 'ZWE', 716, 'ZIMBABWE', 'Зимбабве', NULL)
;

INSERT INTO schema_version VALUES ('01.03')